### PR TITLE
Add a CI pipeline

### PR DESCRIPTION
**Pull request by pieckenst**

### CODE REVIEW

**Comment by aparatext** [comment]
Thanks! I should have made a CI for this already. I'd also like to slightly edit this workflow, so it will make a build for each arch and maybe publish a release to OpenStore once the beta milestone is reached. I'll get back to this shortly after I finish the first version of Ubuntu Info, an almost finished system information app.

Once again, thanks for your contribution!

**Comment by pieckenst** [comment]
Ok i hope now the action will produce some sorta build .. Clickable failed to check for node js in first version of it

**Comment by pieckenst** [comment]
screenshot20220901_002914147
This is what seems to happen in the fork , not sure whats up with that

**Comment by aparatext** [comment]
You just need to run `clickable build --libs` for this arch before building.

**Comment by aparatext** [comment]
Would you mind if I reuse CI configs from https://github.com/walking-octopus/vaults-ut (with an added step for NPM)?

**Comment by pieckenst** [comment]
> Would you mind if I reuse CI configs from https://github.com/walking-octopus/vaults-ut (with an added step for NPM)?

Yeah you can edit mine if ya  wish:) , but i think i got my ci config working now

**Comment by pieckenst** [comment]
Should be mergeable now tbh, its working

**Pull request merged**
